server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ENC(BQGsohp2tGtdi/wU5ck8wDyLGWQinHIZVV4DwG6sfV4aQMnsuYQUMvXvy0LieYzV)
    password: ENC(c/3cfPr8qlb69hAhaYYBth26ltfJ/CnfsKX1aGDatafRHESSeIQch2vDaOVWgy3D)
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

jasypt:
  encryptor:
    password: P@dc#%eve!DaDf4n

adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    binlogName: ""
    position: -1

  kafka:
    topic: ad-search-mysql-data